GET http://localhost:9999

###

POST http://localhost:9999/detect
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="test_cigarette2.jpg"
Content-Type: image/jpeg

< ./images/test_cigarette2.jpg
--boundary--